### ISSUE TITLE
mysql connection error

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#282]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 24, 2010 15:15:03_

What steps will reproduce the problem? (No deterministic sequence to reproduce problem, that I can tell at the moment.)

From time to time i've seen the error mentioned in http://forums.mysql.com/read.php?39,180347,195402#msg-195402 , that is: mysql server is running with all queries successfully processed, but once in a while (looks like after a period of inactivity) the following kind of exception is thrown:

SEVERE: Servlet.service() for servlet ontServlet threw exception
java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2431)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2882)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2871)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3414)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2536)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1383)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.mmisw.ont.MiscDispatcher.listAll(MiscDispatcher.java:306)

This behavior has some consequences in the Ont service and the ORR portal, for example:

- opening ORR and appearing as not logged in (even when I was logged in in my last session and the "rememeber me" enabled.

- getting an empty list of ontologies in the main page

Just refreshing the page (ORR portal) or retrying the operation (Ont) "solves" the problem. So, so far, this has not have any big impact, AFAICT, but it may have in other scenarios, so better look into a complete solution.

Some relevant information:

- MySQL driver: mysql-connector-java-5.1.6-bin.jar (the same one used by the deployed bioportal back-end)

- mysql --version
mysql  Ver 14.7 Distrib 4.1.22, for apple-darwin8.0 (powerpc) 

- one of the comments in the forum above ( http://forums.mysql.com/read.php?39,180347,239082#msg-239082 ) says that they solved the problem by using c3p0. And I see that bioportal has c3p0-0.9.1.2.jar as one of its libraries. However, the bioportal log shows a similar exception.

One possible next step is to upgrade the driver (latest at this moment is 5.1.13 ( http://dev.mysql.com/downloads/connector/j/ )

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=282_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 24, 2010 16:32:06_

mysql-connector-java-5.1.13-bin.jar installed on the MMI ORR deployment.

**Comment by mmisw** [comment]
_From [paul.r.a...@gmail.com](https://code.google.com/u/104064418752273474769/) on September 24, 2010 17:14:40_

Carlos,

This is most likely caused by the connection pooling configuration. We've found that periods of idleness often resulted in connections in the pool becoming stale. When some activity begins, the stale connection is used, resulting in the error above, but then the pool ditches that connection and grabs a new one, meaning that the very next call to come in should process fine.

Our ultimate fix for this is actually getting rolled out to our production machines today, coincidentally. I think our new configuration should work even in the older version of BioPortal. We did end up switching to c3p0 for our pooling library (from dbcp, which has issues under high load).

The configuration we have now does idle connection testing every 180 seconds using a simple "SELECT 1;" query. If the query fails, the connection is removed from the pool. So far it's removed all of our errors, and stands up well under high load.

Here are the relevant files, which should have matching versions in tag 1005 of BioPortal: http://bit.ly/dp7PhP /trunk/tmpl/applicationContext-datasources.prod.xml.tmpl
These are the connection pool settings, the actual values are taken from the build.properties file but you could just copy/paste them here, replacing the "@propertyName@" tokens. http://bit.ly/akYmBT /trunk/tmpl/applicationContext-services.xml.tmpl
You want to make sure the provider_class property is set to use c3p0
\<prop key="hibernate.connection.provider_class">
    org.hibernate.connection.C3P0ConnectionProvider
\</prop>

The c3p0 pooling library you mentioned as being included should work fine as it's the same as the one we're currently using.

Here are the settings from build.properties:
\# Minimum number of Connections a pool will maintain at any 
\# given time.
bioportal.jdbc.c3p0.min_size=10

\# Maximum number of Connections a pool will maintain 
\# at any given time.
bioportal.jdbc.c3p0.max_size=100

\# How many times c3p0 should attempt to acquire a connection
bioportal.jdbc.c3p0.acquire_retry_attempts=5

\# Determines how many connections at a time c3p0 will 
\# try to acquire when the pool is exhausted.
bioportal.jdbc.c3p0.acquire_increment=5

\# If this is a number greater than 0, c3p0 will test 
\# all idle, pooled but unchecked-out connections, 
\# every this number of seconds.
bioportal.jdbc.c3p0.idle_test_period=180

\# Seconds a Connection can remain pooled but unused 
\# before being discarded. Zero means idle connections 
\# never expire.
bioportal.jdbc.c3p0.timeout=28800

\# Absolute age of a connection (regardless of activity).
\# Zero means no limit.
bioportal.jdbc.c3p0.max_connection_age=0

\# Query to use when testing connections.
bioportal.jdbc.c3p0.preferred_test_query=SELECT 1;

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 25, 2010 16:45:00_

Many thanks for this useful information, Paul.

No, tag 1005 does not have the properties used in the mentioned templates. Also, note that the Ont service also accesses the bioportal database directly, so a complete solution needs update on both pieces. In general, I will look into a unified solution when we upgrade to a recent bioportal version; at that point we will be in fact trying the Ont service to be a client of the bioportal exclusively through the provided RESTful interface (ie., not accessing the database directly anymore).

**Cc:** paul.r.alexander  
  **Labels:** -Priority-High Priority-Medium

**Comment by mmisw** [comment]
_From [paul.r.a...@gmail.com](https://code.google.com/u/104064418752273474769/) on September 29, 2010 18:32:12_

Carlos,

The properties I identified above are ones you should be able to add to tag 1005. We haven't changed the way we handle Hibernate connections for quite some time. So, in applicationContext-services.xml.tmpl you should be able to make the sessionFactory bean match our most recent tag and the same with the dataSource bean in datasources.prod.xml.tmpl, except for the dataSource bean you'll want to replace the @token@ syntax with actual values (see below).

\<bean id="dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource" destroy-method="close">
	\<property name="driverClass" value="com.mysql.jdbc.Driver" />
	\<property name="jdbcUrl" value="jdbc:mysql://localhost/bioportal_protege?useUnicode=true&amp;characterEncoding=UTF-8&amp;holdResultsOpenOverStatementClose=true" />
	\<property name="user" value="your_user_name" />
	\<property name="password" value="your_password" />
	\<property name="initialPoolSize">
		\<value>10</value>
	\</property>
	\<property name="minPoolSize">
		\<value>10</value>
	\</property>
	\<property name="maxPoolSize">
		\<value>100</value>
	\</property>
	\<property name="acquireRetryAttempts">
		\<value>5</value>
	\</property>
	\<property name="acquireIncrement">
		\<value>5</value>
	\</property>
	\<property name="idleConnectionTestPeriod">
		\<value>180</value>
	\</property>
	\<property name="maxIdleTime">
		\<value>28800</value>
	\</property>
	\<property name="maxConnectionAge">
		\<value>0</value>
	\</property>
	\<property name="preferredTestQuery">
		\<value>SELECT 1;</value>
	\</property>
\</bean>
