### ISSUE TITLE
concurrency

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#287]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 19, 2010 17:35:35_

Review the proper synchronization mechanisms across the various servlets in the ORR system. It is likely there are concurrency issues that may reveal as traffic to the system increases.  This generic entry may be superseded by more specific entries as appropriate.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=287_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 25, 2010 19:24:05_

Reproducing the problem, see http://marinemetadata.org/mmiorrdeplmtech/orrtests/jmx

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 25, 2010 22:04:06_

**Labels:** -Priority-High Priority-Critical

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 26, 2010 10:59:56_

After noticing an occurrence of this problem, I stopped tomcat; the log showed errors like the following while the tomcat was shutting down:

...
Oct 26, 2010 10:56:40 AM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
SEVERE: The web application [/gpdviz] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@2fa3df]) and a value of type [org.restlet.Context] (value [org.restlet.Context@afb337]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
Oct 26, 2010 10:56:40 AM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
SEVERE: The web application [/gpdviz] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@1f0422]) and a value of type [org.restlet.Response] (value [WAR/null 404 The server has not found anything matching the request URI]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
2010-10-26 10:56:40,317 INFO  [org.oostethys.smlmor.gwt.server.SmlMorServiceImpl] - smlmor 0.0.2pre6 (20101013142908) (null): destroy called.


Oct 26, 2010 10:56:42 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/bioportal] registered the JBDC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 26, 2010 10:56:42 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/bioportal] appears to have started a thread named [MySQL Statement Cancellation Timer] but has failed to stop it. This is very likely to create a memory leak.
Oct 26, 2010 10:56:42 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/bioportal] appears to have started a thread named [Thread-4] but has failed to stop it. This is very likely to create a memory leak.
...

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 26, 2010 11:24:07_

One of the initial errors in the log (catalina.out) is:

Oct 26, 2010 10:52:38 AM org.apache.jasper.runtime.JspFactoryImpl internalGetPageContext
SEVERE: Exception initializing page context
java.lang.IllegalStateException: Cannot create a session after the response has been committed
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2377)
        at org.apache.catalina.connector.Request.getSession(Request.java:2097)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:833)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:844)
        at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:146)
        at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:124)
        at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:107)
        at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:63)
        at org.apache.jsp.index_jsp._jspService(index_jsp.java:45)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:377)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
        at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
        at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:774)
        at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:703)
        at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:896)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
        at java.lang.Thread.run(Thread.java:613)


All of those errors seem to suggest a general memory corruption?

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 26, 2010 17:14:47_

Did adjustments in OntServlet and UriResolver2 to properly handle the OntRequest object so it is thread local. This makes such a request object thread-safe.  Tests using JMeter with multiple concurrent users (30) doing multiple requests (200 each) were successful on my development machine.

MMI Ontology and Term URI Resolver. Version 2.0.13.beta (201010261708)

This should help solve the overall concurrency problem, but revision in other parts of the code is in order.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 27, 2010 16:57:46_

Load test applied on mmisw.org/orr - System much more stable after the recent fixes. More details at: http://marinemetadata.org/mmiorrdeplmtech/orrtests/lt2

**Status:** Started

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 27, 2010 23:07:52_

AdminDispatcher (which manages internal graphs and subGraphOf relations) reviewed and adjusted for proper thread-safety.

MMI Ontology and Term URI Resolver. Version 2.0.14.beta (201010272303)

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 02, 2010 09:49:24_

Lowering priority -- system has proved to be much more stable.

**Labels:** -Priority-Critical Priority-High

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 27, 2014 09:53:15_

Marking fixed has we haven't noted any concurrency issues for a long time.

**Status:** Fixed  
  **Cc:** grayb...@marinemetadata.org
